{
 "title": "My First Tesla Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Battery Percentage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_battery_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estimated Range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_battery_range_est_meter / 1609.344",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dude, Where's my car?",
   "type": "geomap",
   "gridPos": { "h": 26, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "teslafi_latitude", "legendFormat": "{{lat}}" },
    { "expr": "teslafi_longitude", "legendFormat": "{{lon}}" }
   ]
  },
  {
   "title": "Tesla Inside Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(teslafi_inside_temperature * 1.8)+ 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2019 Tesla Model 3",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "options": {
    "content": "<img src=\"https://i.imgur.com/4wEpb74.png\" alt=\"Foreground Image\">\n\n\n"
   }
  },
  {
   "title": "Tesla OutsideTemperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(teslafi_outside_temperature * 1.8)+ 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Speed MPH",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_speed_kmh / 1.60933", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Charging Rate (MPH)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_charge_rate / 1.60933", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Locked/Unlocked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_locked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Odometer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_odometer_meter_total/1609.344",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}